### DISCUSSION TITLE
Skip Chrome Onboarding

### DISCUSSION THREAD

**Discussion by riglar** [devicecloud-dev/docs#14] [Ideas]
When opening links on a new device Google Chrome pushes the user through several onboarding screens.

Ideally, Device Cloud's devices should skip this onboarding so that users don't need to account for it in their tests.

[Discord Thread](https://discord.com/channels/1206536148650950736/1206536149254799422/1328663475718979616)

**Comment by aruudboy** [comment]
I don't know if this is helpful, but my team have solved this by running a helper in relevant tests in our project. The helper has the following content:

```
appId: ${APP_ID}
---
- runFlow:
    when:
      visible: Welcome to Chrome
    commands:
      - tapOn:
          text: "Accept & continue"
          optional: true
      - tapOn:
          text: "Use without an account"
          optional: true
      - tapOn:
          text: "No thanks"
          optional: true

- runFlow:
    when:
      visible: "Chrome notifications make things easier"
    commands:
      - tapOn:
          text: "No thanks"
          optional: true

```
